# SPDX-FileCopyrightText: Canonical Ltd.
#
# SPDX-License-Identifier: Apache-2.0

name: Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.96.0

      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@v2

      - name: Install Task
        run: sudo snap install --classic task

      - name: Install reuse tool
        run: sudo apt-get update && sudo apt-get install -y reuse

      - name: Run validation
        timeout-minutes: 10
        run: task validate
