# SPDX-FileCopyrightText: Canonical Ltd.
#
# SPDX-License-Identifier: Apache-2.0

name: Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  reuse:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v5

  validate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@1.96.0

      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@v2

      - name: Install Task
        run: sudo snap install --classic task

      # REUSE compliance is checked in a separate job using fsfe/reuse-action
      - name: Run validation
        timeout-minutes: 10
        run: task validate SKIP_REUSE=true
